name: Build Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    - name: Create Release
      uses: ncipollo/release-action@v1.10.0
      with:
        bodyFile: "release_notes.md"